## Configuracion de Instancia
server:
  port: 8092
  error:
    include-stacktrace: on_param

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: books-payments

## Configuracion de Spring
spring:
  application:
    name: books-payments
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

## Configuracion secundaria (custom)
getBook:
  url: http://books-catalogue/libros/%d
patchBook:
  url: http://books-catalogue/libros/%d
